### ISSUE TITLE
Configuration for External URL in Deployment

### ISSUE THREAD

**Issue by trisongz** [autokitteh/autokitteh#854]
Hi,

I've been exploring this project and love the direction and how simple it is to use. I'm looking for some direction and guidance on how to deploy into a production environment.

I've been able to deploy and test this locally, both within host (macos) and docker image (built). 

However, I'm running into an issue when moving to a self-hosted deployment, mainly with the frontend/web trying to reach the backend. I can't seem to find a configuration where you're able to modify the backend url `localhost:9980` that the frontend tries to reach.

Additionally, when trying to do a full prod deployment, with external `temporal self-hosted`, `postgres`, and `redis` - there's also some different issues with the encryption requirement for `temporal data-converter` [(src)](https://github.com/autokitteh/autokitteh/blob/main/internal/backend/temporalclient/config.go#L53), which doesn't happen in `--mode=dev`

Assuming that we're using a FQDN for both frontend and backend, we'd ideally have it be:

```yaml
frontend: https://web.example.com
backend: https://web-api.example.com
```
Thanks!

**Comment by efiShtain** [comment]
Hey @trisongz 

Super excited to hear that you love the direction and simplicity :)

## Regarding the UI
you have to rebuild the UI with a build variable pointing to your backend endpoint

Try following this procedure and let me know if you have any issue
https://github.com/autokitteh/web-platform/blob/main/README.md#environment-setup-

The UI is in the web-platform repo


## Regarding backend external dependencies

### Postgres
set the following env variables 
```bash
AK_DB__TYPE=postgres
AK_DB__DSN="host=0.0.0.0 port=5432 user=postgres dbname=ak sslmode=disable" # match the args for your postgres endpoint
```

you can also set ```AK_DB__AUTO_MIGRATE``` to true so migrations would run automatically if there are changes. We do our best to be backwards compatible but since we are not still in fast development mode we can't guarantee it.

### Temporal
Please set the following env variables to work with a managed temporal environment with certificates. If your temporal server doesn't require certificates, set ```AK_TEMPORALCLIENT__TLS__ENABLED``` to false, then you don't need to provide certificate and key

```bash
        AK_TEMPORALCLIENT__HOSTPORT="",
        AK_TEMPORALCLIENT__NAMESPACE= "",
        AK_TEMPORALCLIENT__TLS__CERTIFICATE="",
        AK_TEMPORALCLIENT__TLS__KEY="",
        AK_TEMPORALCLIENT__TLS__ENABLED= "true",
```

#### Data Converters
To disable the data converter key requirements set the following env var
```bash
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__ENCRYPT=false
```

if you plan to use the conversion keys, keep the default set to true and add the following variable, 
```bash
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__KEYS=""
```
keys variable format is 
```go
// Comma-separated list of key names and values.
	// First key is used for encryption, others are used only for decryption.
	// Format: "key1=<64 char hex>,keys=<64 char hex>"
	// Example: "key1=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef,key2=abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
```

### Redis
Redis store is only required by some of our integrations, if you wish to set it up, configure the following env variable

```bash
AK_STORE__SERVER_URL="" # should be a valid Redis endpoint like redis://localhost:6379
```



Let me know if you need any more help / have any questions / suggestions

**Comment by trisongz** [comment]
Hey @efiShtain , thanks for providing the reference env vars and instructions for the `web-platform` build. I was able to get much further along.

However, I've been running into an issue with the frontend trying to communicate with the backend with some CORS issues:

`CORS error | fetch | transport.grpc.api.ts:24`

The container is being started up with the arguments: `up --mode=default`. 
**Env Vars:**

We've set the env vars similar to the below:

```
AK_DB__TYPE=postgres
AK_DB__DSN=host=pg.db.svc.cluster.local port=5432 dbname=autokitteh sslmode=disable user=autokitteh password=...
AK_DB__AUTO_MIGRATE=true

AK_TEMPORALCLIENT__HOSTPORT=temporal-service.workflows.svc.cluster.local:7233
AK_TEMPORALCLIENT__NAMESPACE=autokitteh
AK_TEMPORALCLIENT__TLS__ENABLED=false
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__ENCRYPT=false
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__KEYS=""

AK_HTTP__CORS__ALLOWED_ORIGINS="*"
AK_HTTP__CORS__ALLOW_CREDENTIALS=true
AK_HTTP__CORS__ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
AK_HTTP__CORS__ALLOWED_HEADERS="*"
AK_HTTP__SERVICE_URL=https://api.sub.domain.com

AK_AUTHJWTTOKENS__SIGN_KEY=....
AK_AUTHLOGINHTTPSVC__GOOGLE_OAUTH__ENABLED=true
AK_AUTHLOGINHTTPSVC__GOOGLE_OAUTH__CLIENT_ID=...
AK_AUTHLOGINHTTPSVC__GOOGLE_OAUTH__CLIENT_SECRET=...

AK_AUTHLOGINHTTPSVC__GOOGLE_OAUTH__REDIRECT_URL=https://app.sub.domain.com/oauth/redirect/google
AK_AUTHSESSIONS__UI_DOMAIN=app.sub.domain.com
AK_AUTHHTTPMIDDLEWARE__REQUIRED=true
AK_AUTHSESSIONS__COOKIE_KEYS=...
AK_HTTP__H2C__ENABLE=false
AK_STORE__SERVER_URL=redis://@redis.db.svc.cluster.local:6379/2
WEBHOOK_ADDRESS=api.sub.domain.com

AK_SECRETS__PROVIDER=db
AK_BANNER__SHOW=true
AK_HTTP__ADDR=0.0.0.0:9980
AK_WEBPLATFORM__PORT=9982
```

For additional context, we are running `autokitteh` within kubernetes, and exposing the services on `:9980` and `:9982` publicly via `nginx-ingress`. 

**Ingress:**

Both services are being exposed via TCP/HTTP. I did notice that there was reference to it being GRPC, but I wasn't sure whether `:9980` should be exposed explicitly as GRPC.

```
app.sub.domain.com: autokitteh-service:9982 (web)
api.sub.domain.com: autokitteh-service:9980 (grpc/http)
```

I feel like I'm missing something, as I'm not able to explicitly set the `gRPC/HTTP: localhost:9980` to `gRPC/HTTP: 0.0.0.0:9982`. Is there any other env vars or configuration that I should be setting?

Thanks!

**Comment by trisongz** [comment]
Shoutout to @efiShtain and the autokitteh team. They reached out to me and we worked through and were able to debug the deployment.

Below is some additional documentation for anyone looking for reference in how to deploy autokitteh in Kubernetes from my learnings.

## Context 

The following is our k8s environment. 

```
Distro: talos
Version: 1.31
Ingress: nginx
```

My desired use case was to self-host `autokitteh` with auth to allow internal org members to use, as well as utilizing our own self-hosted `temporal` and accessible via `app.sub.domain.com`. 

## Prerequisites

- [Descope Account](https://www.descope.com/) (free) - While we use `google-oauth` internally for most things, it is not currently fully tested, and you can use descope to piggyback onto `google-oauth` as your provider.
- 2 separate domains, such that `app.domain.com` and `api.domain.com` are available, or `app.sub.domain.com` and `api.sub.domain.com`.  As long as they are on the same subdomain / domain path, it will work. We'll refer to this as `app_domain` and `api_domain`.
- Be able to compile the `autokitteh-web` and `autokitteh` repos.

## Building the Image

Below is how I have my workdir setup

```
apps/
  - autokitteh/
     - build_web.sh
     - build_image.sh
  - autokitteh-web/
     - .env
```

To start with, you will need to build the web image. Following the directions in the [readme](https://github.com/autokitteh/web-platform), you will to set your `autokitteh-web/.env` file. The following content will work

```
# path: autokitteh-web/.env
# if you don't have TLS/SSL, it should just be http://
VITE_HOST_URL=https://{api_domain}
# If you don't need auth, you can skip the following two variables
VITE_AUTH_ENABLED=true
# you should get this from your descope account.
VITE_DESCOPE_PROJECT_ID=...
```

For the `autokitteh/Dockerfile`, you need to make a slight modification. 

```Dockerfile
# path: autokitteh/Dockerfile
# remove the `make webplatform` to look like the following
RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=bind,target=.,rw \
    <<EOF
    export VERSION_PKG_PATH="go.autokitteh.dev/autokitteh/internal/version"
    export TIMESTAMP="$(date -u "+%Y-%m-%dT%H:%MZ")"
    export LDFLAGS="-X "${VERSION_PKG_PATH}.Version=$(cat .version || echo)" -X "${VERSION_PKG_PATH}.Time=${TIMESTAMP}" -X "${VERSION_PKG_PATH}.Commit=$(cat .commit || echo)""
    CGO_ENABLED=0 go build -o /bin/ak -ldflags="${LDFLAGS}" ./cmd/ak
EOF
```

I have the contents of `autokitteh/build_web.sh`:

```bash
# path: autokitteh/build_web.sh
# Build the Autokitteh Zip File and Moves it to the Web Platform

HERE=$(pwd)
CURRENT_VERSION=$(cat $HERE/web/webplatform/VERSION | cut -d ' ' -f 1)
echo "Current Version: $CURRENT_VERSION"
# https://github.com/autokitteh/web-platform

# Remove the old version
rm -rf ./web/webplatform/autokitteh-web-v*.zip

# Build the Autokitteh Web Platform
cd ../autokitteh-web && git pull
rm -rf ./dist

echo "Building Autokitteh Web Platform"
npm install
npm run build

echo "Zipping Autokitteh Web Platform"
zip -r $HERE/web/webplatform/autokitteh-web-v${CURRENT_VERSION}.zip ./dist/

cd $HERE

git pull
echo "Completed"
```

And the contents of `autokitteh/build_image.sh`:

```
# path: autokitteh/build_image.sh
# Build the Autokitteh Docker Image

DO_BUILD_WEB=${DO_BUILD_WEB:-true}
DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG:-latest}

HERE=$(pwd)

DOCKER_REPO=yourrepo/autokitteh
DOCKER_TAG=${DOCKER_REPO}:${DOCKER_IMAGE_TAG}

export DOCKER_BUILDKIT=1

cd $HERE
git pull
if [ "$DO_BUILD_WEB" == "true" ]; then
    echo "Building Web Platform"
    bash $HERE/build_web.sh
    echo "Done"
fi

cd $HERE
docker \
    buildx build \
    -t ${DOCKER_TAG} \
    --file ${HERE}/Dockerfile \
    --platform linux/amd64 \
    --target final \
    --push \
    ${HERE}
```

**Important: Running the scripts assumes you have `autokitteh/` as your cwd**

Then you can build and push the images with

```bash
cd autokitteh
bash build_image.sh
```

### Deployment

Finally, after you have your images compiled, you can deploy with your preferred method. 

The most important components are the `env vars` and `ingress`.

This took a lot of trial and error, but finally worked.

This may not be an exhaustive list / ref but should do.

```env
# secrets.env
AK_DB__TYPE=postgres

# Your Postgres DSN
AK_DB__DSN=host=pg.db.svc.cluster.local port=5432 dbname=autokitteh sslmode=disable user=autokitteh password=...
AK_DB__AUTO_MIGRATE=true

# If you don't want to use a self-hosted temporal, comment out the following
AK_TEMPORALCLIENT__HOSTPORT=temporal-service.workflows.svc.cluster.local:7233
AK_TEMPORALCLIENT__NAMESPACE=autokitteh
AK_TEMPORALCLIENT__TLS__ENABLED=false
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__ENCRYPT=false
AK_TEMPORALCLIENT__DATA_CONVERTER__ENCRYPTION__KEYS=""

# This part is super important. Ensure that you have both `api_domain` and `app_domain` here.
AK_HTTP__CORS__ALLOWED_ORIGINS=https://{api_domain},https://{app_domain}
AK_HTTP__CORS__ALLOW_CREDENTIALS=true
AK_HTTP__CORS__ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS,HEAD
AK_HTTP__CORS__ALLOWED_HEADERS="*"
AK_HTTP__SERVICE_URL=https://{api_domain}

# The following should be a 64-char alpha numeric key
AK_AUTHJWTTOKENS__SIGN_KEY=abc123..{64}

# If you don't care for auth, disable the following
AK_AUTHLOGINHTTPSVC__DESCOPE__ENABLED=true
AK_AUTHLOGINHTTPSVC__DESCOPE__PROJECT_ID={your_descope_project_id}

# Add for debugging
AK_PYTHONRT__LOG_RUNNER_CODE=true
AK_PYTHONRT__LOG_BUILD_CODE=true
AK_LOGGER__LEVEL=debug

# this should be one level up from your app/api domains.
# if your api_domain is api.sub.domain.com then the value should be sub.domain.com
# if your api_domain is api.domain.com then the value should be domain.com
AK_AUTHSESSIONS__UI_DOMAIN={domain}
# set to false if you don't care for auth
AK_AUTHHTTPMIDDLEWARE__REQUIRED=true

# These should be two comma separated 64-char random token.
AK_AUTHSESSIONS__COOKIE_KEYS=abc...{64},abc....{64}

# THIS SHOULD ALWAYS BE TRUE
# otherwise you will run into bugs with running the worker
# AK_HTTP__H2C__ENABLE=true

# Set this to your redis deployment
AK_STORE__SERVER_URL=redis://{auth}@redis-cluster.db.svc.cluster.local:6379/2

WEBHOOK_ADDRESS={api_domain}
AK_SECRETS__PROVIDER=db
AK_BANNER__SHOW=true
```

And the following should be the entrypoint for the container:

```yaml
# deployment.yaml
- name: autokitteh
   image: yourrepo/autokitteh:latest
   args: ["up", "--mode=dev"]
```

Finally, for nginx-ingress annotations:


```yaml
# ingress.yaml
# I'm not sure if ALL of these are needed but it seems to work
nginx.ingress.kubernetes.io/cors-allow-headers: >-
      DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Accept,Access-Control-Allow-Origin,Token,X-Cache-Disabled,X-No-Cache,Cache-Disabled,X-Accept-Content-Transfer-Encoding,X-Accept-Response-Streaming,X-User-Agent,X-Grpc-Web,Connect-Protocol-Version,Connect-Timeout-Ms

nginx.ingress.kubernetes.io/cors-allow-methods: '*'
nginx.ingress.kubernetes.io/cors-allow-origin: 'https://{app_domain},https://{api_domain}'
```

Hopefully this guide helps others out there who might be looking to self-host!

Again, thanks to the autokitteh team for the support!
