### ISSUE TITLE
I can't reach the website locally

### ISSUE THREAD

**Issue by dolby360** [autokitteh/autokitteh#915]
## Summary

After building the container using Docker Compose, everything seems fine. Auttokitteh reports it is available on port 9982, but nothing is displayed when accessing the port.

## Steps to reproduce
1. git reset to latest commit 304c9ed45c45bdc385a923ef79093259ab9f10ed
2.
```bash 
docker compose build
docker compose up
```
Open website on http://localhost:9982/

## Expected behavior
The website should be displayed.

## Actual behavior
Nothing is displayed.

**Comment by itayd** [comment]
you should do `make ak`. this will fetch the latest webplatform and make it work. you probably did `make bin`?

**Comment by itayd** [comment]
you could also `make webplatform` before `make bin`.

**Comment by itayd** [comment]
oh, i see now you're using docker. looking into it.
